// React/intalent-final/src/pages/create-profile.js
import React from 'react'
import './create-profile.css'
import { getAuth } from "firebase/auth";
import axios from 'axios';


class Crearperfil extends React.Component {
    //const { register, errors, handleSubmit } = useForm();
    constructor(props) {
        super(props);
        this.state = {
            name: '',
            dob: '',
            gender: '',
            city: '',
            country: '',
            topics: '',
            bio: '',
        };
        this.topics = [
            'Naturaleza',
            'Ir de cañas',
            'Juegos de mesa',
            'Bailar',
            'Mascotas',
            'Picnic',
            'Idiomas',
        ];

        //truco para estar siempre actualizado con respecto al formulario
        this.handleChange = this.handleChange.bind(this);
        this.handleSubmit = this.handleSubmit.bind(this);
    }

    //Lo usaremos cuando cambien los valores del formulario
    //este truco permite que todos empleen el mismo handler
    handleChange(event) {
        const name = event.target.name;
        const value = event.target.value;

        //Desesctructuracion (ES6)
        this.setState({
            [name]: value
        });
    }

    // --------------------
    // SERVICIOS CON AXIOS (POST)
    // --------------------

    handleSubmit = (event) => {
        //Para no propagar el formulario
        event.preventDefault();
        //leo datos
        const persona = {
            loginId: getAuth().currentUser?.uid,
            gender: this.state.gender,
            name: this.state.name,
            city: this.state.city,
            country: this.state.country,
            dob: this.state.dob,
            bio: this.state.bio,
            likes: [],
            dislikes: [],
            topics: [],
        };
        //let history = useHistory();

        axios
            .post(`http://localhost:8080/api/crear-perfil`, persona)
            .then((resp) => {
                console.log('perfil creado')

                // navi("http://localhost:4200/main");
                //history.push('/list-books');
            })
            .catch((error) => {
                this.setState({ errorMessage: error.message });
                console.error('Ha habido un error', error);
            });
    }

    render() {
        return (
            <div className="container create" >
                <h1 className="h1">Crear Perfil</h1>

                <form onSubmit={this.handleSubmit}>

                    <div className="form-group">
                        <label for="create--name">Nombre</label>
                        <input
                            className="form-control"
                            type="text"
                            name="name"
                            onChange={this.handleChange}
                            required
                        />
                    </div>

                    <div className="form-group">
                        <label for="create--age">Año de nacimiento</label>
                        <input
                            className="form-control"
                            type="date"
                            name="dob"
                            onChange={this.handleChange}
                            required
                        />
                    </div>

                    <div className="form-group checkgender">
                        <label for="create--gender">Mujer</label>
                        <input
                            className="form-control"
                            type="radio"
                            value="Mujer"
                            name="gender"
                            onChange={this.handleChange}
                            required

                        />
                        <label>Hombre</label>
                        <input
                            className="form-control"
                            type="radio"
                            name="gender"
                            value="Hombre"
                            onChange={this.handleChange}
                            required
                        />
                    </div>

                    <div className="form-group">
                        <label for="create--city">Ciudad</label>
                        <input
                            className="form-control"
                            type="text"
                            name="city"
                            onChange={this.handleChange}
                            required
                        />
                    </div>

                    <div className="form-group">
                        <label for="create--country">País</label>
                        <input
                            className="form-control"
                            type="text"
                            name="country"
                            onChange={this.handleChange}
                            required
                        />
                    </div>

                    <div className="form-group">
                        <label for="create--picture">Foto</label>
                        <input
                            className="form-control"
                            type="file"
                            name="create--image"
                            onChange={this.handleChange}
                            required
                        />
                        {/* <img
                                    //  [src]="this.persona.image"
                                    //  height="200"
                                    // *ngIf="this.persona.image"
                                    //  /> */}
                    </div>


                    <div className="form-group">
                        <span>Intereses</span>
                        {this.topics.map((topic) =>
                        (
                            <div>
                                <input
                                    id={topic}
                                    className="form-control"
                                    type="checkbox"
                                    name="topics"
                                    onChange={this.handleChange}
                                    required
                                />
                                <label for={topic}> {topic}</label>
                            </div>
                        ))}
                    </div>


                    <div className="form-group">
                        <label for="create--text">Descripcion</label>
                        <textarea
                            className="form-control"
                            type="textarea"
                            name="bio"
                            onChange={this.handleChange}
                            required
                        />
                    </div>

                    <div className="form-group">
                        <button className="submit" type="submit">
                            Busca tu amor
                        </button>
                    </div>
                </form>
            </div >
        );

    }

}

// --------------------
// RENDER
// --------------------

//en esencia es lo que tenia en Angular en el HTML + render()

export default Crearperfil;

// Front/src/app/components/create-profile/create-profile.component.ts
import { Component, OnInit, NgZone } from '@angular/core';
import { CrudServicesService } from 'src/app/services/crud-services.service';
import { Router } from '@angular/router';
import { Persona } from '../../models/user';
import { AuthService } from 'src/app/services/auth.service';
import { AngularFireAuth } from '@angular/fire/compat/auth';

@Component({
    selector: 'app-create-profile',
    templateUrl: './create-profile.component.html',
    styleUrls: ['./create-profile.component.scss'],
})
export class CreateProfileComponent implements OnInit {
    persona: Persona = {} as Persona;
    loginId: any;
    userId: any;
    topicsList = [
        'Naturaleza',
        'Ir de cañas',
        'Juegos de mesa',
        'Bailar',
        'Mascotas',
        'Picnic',
        'Idiomas',
    ];
    test = [];

    constructor(
        private crudService: CrudServicesService,
        private router: Router,
        private ngZone: NgZone,
        public userFirebase: AuthService,
        public firebase: AngularFireAuth
    ) {
        firebase.authState.subscribe((user) => {
            this.userId = String(user?.uid);
        });
    }

    // Recogide de información de los inputs
    logName(x: any) {
        this.persona.name = x.value;
    }
    logAge(x: any) {
        this.persona.dob = x.value;
    }
    logGender(x: any) {
        this.persona.gender = x.value;
    }
    logCity(x: any) {
        this.persona.city = x.value;
    }
    logCountry(x: any) {
        this.persona.country = x.value;
    }
    logImage(event: any) {
        let reader = new FileReader();
        reader.readAsDataURL(event.target.files[0]);
        reader.onload = () => {
            this.persona.image = reader.result;
            console.log(this.persona.image);
        };
    }

    logTopic(x: any) {
        console.log('x.name', x.name);
        if (x.value) {
            this.persona.topics.push(x.name);
        }
        console.log(this.persona.topics);
    }
    logBio(x: any) {
        this.persona.bio = x.value;
    }

    // Uso conjunto de los datos guardados en el objeto
    log(): any {
        this.persona.loginId = this.userId;
        this.crudService.addnewuser(this.persona).subscribe({
            next: (any) => {
                console.log('Data added successfully!');
                this.ngZone.run(() => this.router.navigateByUrl('/main'));
            },
            error: (err) => {
                console.log(err);
            },
        });
        console.log(this.persona);
    }

    ngOnInit() {}
}

<div class="container create">
    <form class="create--form">
        <div class="form-group">
            <label for="create--name">Nombre</label>
            <input
                required
                ngModel
                #userName="ngModel"
                type="text"
                name="create--name"
                id="create--name"
                class="form-control"
                (change)="logName(userName)"
            />
            <div
                class="alert alert-danger"
                *ngIf="userName.touched && !userName.valid"
            >
                Es necesario escribir tu Nombre
            </div>
        </div>
        <div class="form-group">
            <label for="create--age">Año de nacimiento</label>
            <input
                required
                ngModel
                #userAge="ngModel"
                type="date"
                name="create--age"
                id="create--age"
                class="form-control"
                (change)="logAge(userAge)"
            />
        </div>
        <div class="form-group">
            <label for="create--gender">Género</label>
            <select
                required
                ngModel
                #userGender="ngModel"
                name="create--gender"
                id="create--gender"
                class="form-control"
                (change)="logGender(userGender)"
            >
                <option value="male">Hombre</option>
                <option value="female">Mujer</option>
            </select>
        </div>
        <div class="form-group">
            <label for="create--city">Ciudad</label>
            <input
                required
                ngModel
                #userCity="ngModel"
                type="text"
                name="create--city"
                id="create--city"
                class="form-control"
                (change)="logCity(userCity)"
            />
            <div
                class="alert alert-danger"
                *ngIf="userName.touched && !userName.valid"
            >
                Es necesario escribir tu Ciudad
            </div>
        </div>
        <div class="form-group">
            <label for="create--country">Pais</label>
            <input
                required
                ngModel
                #userCuntry="ngModel"
                type="text"
                name="create--country"
                id="create--country"
                class="form-control"
                (change)="logCountry(userCuntry)"
            />
            <div
                class="alert alert-danger"
                *ngIf="userName.touched && !userName.valid"
            >
                Es necesario escribir tu Pais
            </div>
        </div>
        <div class="form-group">
            <label for="create--country">Foto</label>
            <input
                required
                type="file"
                name="create--image"
                id="create--image"
                class="form-control"
                (change)="logImage($event)"
            />
            <img
                [src]="this.persona.image"
                height="200"
                *ngIf="this.persona.image"
            />
            <div
                class="alert alert-danger"
                *ngIf="userName.touched && !userName.valid"
            >
                Es necesario subir una foto.
            </div>
        </div>

        <div class="form-group">
            <span>Intereses</span>
            <div *ngFor="let topic of topicsList">
                <input
                    ngModel
                    #userTopic="ngModel"
                    type="checkbox"
                    id="topic-{{ topic }}"
                    name="{{ topic }}"
                    value="{{ topic }}"
                    (change)="logTopic(userTopic)"
                />
                <label for="topic-{{ topic }}"> {{ topic }}</label>
            </div>
        </div>
        <div class="form-group">
            <label for="create--text">Descripción</label>
            <textarea
                required
                ngModel
                #userBio="ngModel"
                name="create--text"
                id="create--text"
                cols="30"
                rows="10"
                (change)="logBio(userBio)"
            ></textarea>
        </div>
        <button class="btn btn-primary" (click)="log()">Continuar</button>
        <!-- <input type="submit" value="Continuar" routerLink="../main" /> -->
    </form>
</div>
